[tool.poetry]
name = "litterbox"
version = "0.1.0"
description = ""
authors = ["Charlie Groves <c@sevorg.org>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
hyperlinked_ripgrep = 'litterbox.hrg:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
